
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ASIGNAR COMDOB CORDER CORIZQ DISTINTO DIV DIVR DOSPUNTO ENDL ENTERO FOR GET IDENTIFICADOR IGUAL INCLUDE INT INT LLADER LLAIZQ MAIN MAYORDER MAYORIGUAL MAYORIZQ MAYORQUE MENORIGUAL MENORQUE MINUSMINUS MODULO MULT NAMESPACE NOT NUMERAL OR PARDER PARIZQ PLUSPLUS POTENCIA PRINTF PUNTO PUNTOCOMA RESERVADA RESTA RETURN SI SINO STD SUMA SYSTEM USING VOID WHILE\n    expresion : NUMERAL INCLUDE MENORQUE STD IDENTIFICADOR PUNTO IDENTIFICADOR MAYORQUE MAYORQUE\n              | INT MAIN PARIZQ VOID PARDER PARDER \n              | LLAIZQ LLAIZQ\n              | PRINTF PARIZQ COMDOB IDENTIFICADOR IDENTIFICADOR DIVR IDENTIFICADOR COMDOB PARDER PUNTOCOMA PUNTOCOMA\n              | RETURN ENTERO PUNTOCOMA PUNTOCOMA\n              | LLADER LLADER\n\n    '
    
_lr_action_items = {'NUMERAL':([0,],[2,]),'INT':([0,],[3,]),'LLAIZQ':([0,4,],[4,10,]),'PRINTF':([0,],[5,]),'RETURN':([0,],[6,]),'LLADER':([0,7,],[7,13,]),'$end':([1,10,13,21,26,32,35,],[0,-3,-6,-5,-2,-1,-4,]),'INCLUDE':([2,],[8,]),'MAIN':([3,],[9,]),'PARIZQ':([5,9,],[11,15,]),'ENTERO':([6,],[12,]),'MENORQUE':([8,],[14,]),'COMDOB':([11,29,],[16,31,]),'PUNTOCOMA':([12,17,33,34,],[17,21,34,35,]),'STD':([14,],[18,]),'VOID':([15,],[19,]),'IDENTIFICADOR':([16,18,20,25,27,],[20,22,24,28,29,]),'PARDER':([19,23,31,],[23,26,33,]),'PUNTO':([22,],[25,]),'DIVR':([24,],[27,]),'MAYORQUE':([28,30,],[30,32,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> NUMERAL INCLUDE MENORQUE STD IDENTIFICADOR PUNTO IDENTIFICADOR MAYORQUE MAYORQUE','expresion',9,'p_expresion','analizador_sintactico.py',11),
  ('expresion -> INT MAIN PARIZQ VOID PARDER PARDER','expresion',6,'p_expresion','analizador_sintactico.py',12),
  ('expresion -> LLAIZQ LLAIZQ','expresion',2,'p_expresion','analizador_sintactico.py',13),
  ('expresion -> PRINTF PARIZQ COMDOB IDENTIFICADOR IDENTIFICADOR DIVR IDENTIFICADOR COMDOB PARDER PUNTOCOMA PUNTOCOMA','expresion',11,'p_expresion','analizador_sintactico.py',14),
  ('expresion -> RETURN ENTERO PUNTOCOMA PUNTOCOMA','expresion',4,'p_expresion','analizador_sintactico.py',15),
  ('expresion -> LLADER LLADER','expresion',2,'p_expresion','analizador_sintactico.py',16),
]
